### ISSUE TITLE
添加“收藏”图标和实现“收藏”功能

### ISSUE THREAD

**Issue by Zhou-Peican** [OptimalOrange/CoolTechnologies#12]
需要在ListCommentsFragment中完成收藏，就是播放视频中的在’评论‘标题右边有个登陆图标处（这里应为收藏图标，我没图标就借用了登陆图标，但这里是@+id/favorite）。

**Comment by Bai-Jie** [comment]
“添加收藏”功能已由 commit 809889095fdc37dde477674de9277b51bddda277 实现，在 commit f7d474aa1c8e8e3acce43c0bafc4fc7ca86d5b44 进行了改进。
