### ISSUE TITLE
“热门”页面和“搜索”页面的布局优化

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#21]
`StaggeredGridView`在联想手机上比例异常。
改用更整齐的布局设计。

**Comment by Zhou-Peican** [comment]
此issue的解决是在提交：79de06736d8c718ad4f1079773d3c0e4571ba491

**Comment by Zhou-Peican** [comment]
此issue的解决增加提交： c3a7189b22b4d823e638b77fa3a2b0cc22540b79
