### ISSUE TITLE
关于“多第三方网站支持”的讨论

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#79]
断言：
- 以driver插件的形式，添加第三方网站支持

待讨论：
- 收藏的视频，保存在我们的系统内部好，还是保存在第三方网站好？

**Comment by Bai-Jie** [comment]
视频收藏的方式，我想到的有：

1. 根据视频来源网站，向那个网站发送收藏指令
2. 在本系统内保存收藏的视频，不修改来源网站的收藏夹
3. 1和2的结合。在本系统内保存收藏的视频，同时尝试向来源网站发送收藏指令

**Comment by bai-jie** [comment]
同 #80 ，取消
