### ISSUE TITLE
新功能/特性讨论

### ISSUE THREAD

**Issue by Bai-Jie** [OptimalOrange/CoolTechnologies#80]
相关文档：
- https://github.com/OptimalOrange/CoolTechnologies/blob/2.x/docs/0.feature.md

**Comment by Bai-Jie** [comment]
是否需要“编辑推荐”功能？

**Comment by Bai-Jie** [comment]
刚和 @Zhou-Peican 讨论，#29 的Banner与“编辑推荐”类似。Banner可以看成少数的（2-4个）“编辑推荐”。
关于这个，按#29的规划来。
不另增单独的“编辑推荐”功能。

**Comment by bai-jie** [comment]
不再添加新功能
